version: '3.1'

services:
  space-y-server:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      NODE_ENV: 'production'
      PORT: '5000'
    ports:
      - '5000:5000'
    restart: always

  postgres:
    container_name: pg-server
    image: postgres:11
    ports:
      - '54322:${POSTGRES_PORT}'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nginx:
    image: nginx
    depends_on:
      - space-y-server
      - postgres
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
