export enum USER_ACTIONS {
  SET_USER_DATA = 'USER_SET_USER_DATA',
  GET_USER_DATA_FROM_SERVER = 'USER_GET_USER_DATA_FROM_SERVER',
  PENDING = 'USER_SET_PENDING',
  ERROR = 'USER_SET_ERROR',
  AUTH = 'USER_AUTH',
  LOGOUT = 'USER_LOGOUT'
}
