import { GAME_SETTINGS } from 'game/constants';

export const GAME_OPTIONS = {
  GAME_AREA_WIDTH: GAME_SETTINGS.GAME_AREA_WIDTH,
  GAME_AREA_HEIGHT: GAME_SETTINGS.GAME_AREA_HEIGHT,
  HULL_STRENGTH_LABLE: 'HULL',
  DISTANCE_LABLE: 'DISTANCE',
  GAME_OVER_TITLE: 'You\'ve crashed',
  GAME_OVER_SCORE_TITLE: 'Distance passed:',
};
