export const GAME_OPTIONS = {
  CANVAS_WIDTH: 375,
  CANVAS_HEIGHT: 667,
  HULL_STRENGTH_LABLE: 'HULL',
  DISTANCE_LABLE: 'DISTANCE',
  GAME_OVER_TITLE: 'You\'ve crashed',
  GAME_OVER_SCORE_TITLE: 'Distance passed:',
};
