export const GAME_OPTIONS = {
  GAME_AREA_WIDTH: 375,
  GAME_AREA_HEIGHT: 667,
  HULL_STRENGTH_LABLE: 'HULL',
  DISTANCE_LABLE: 'DISTANCE',
  GAME_OVER_TITLE: 'You\'ve crashed',
  GAME_OVER_SCORE_TITLE: 'Distance passed:',
};
