export enum USER_ACTIONS {
  SET_USER_DATA = 'USER_SET_USER_DATA',
  GET_USER_DATA_FROM_SERVER = 'USER_GET_USER_DATA_FROM_SERVER',
  PENDING = 'USER_SET_PENDING',
  ERROR = 'USER_SET_ERROR',
  AUTH = 'USER_AUTH',
  LOGOUT = 'USER_LOGOUT',
}

export enum GAME_ACTIONS {
  SET_IS_GAME_STARTED = 'GAME_SET_IS_GAME_STARTED',
  SET_IS_GAME_PAUSED = 'GAME_SET_IS_GAME_PAUSED',
  SET_IS_GAME_OVER = 'GAME_SET_IS_GAME_OVER',
  SET_LAST_SCORE = 'GAME_SET_LAST_SCORE',
}
