name: Deploy

on:
  push:
    branches:
      - test-deploy

jobs:
  push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: supergrovernn/spacey:latest
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 178.154.192.180
          username: booger1
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDtrRwjEPmIMiiEHaeoWnOn/fza4vCOtJAb63LMmeJFwyPOMps6NWN52HShcWAg5ye0iptHJ7jf3ipzl7mAYm7zGgmKOs2HdgaZ5/P3YkMwYP442JIrhdNVDLKcFRhNSy8km+AFa/jHkQbH3L3ijo/P9aYpP6c6pV5oKc1//PtIzS3UTN1XuoJBGz9sUBhNEptLZXJgvVQNTBvQ0qGdNBk+l+zu4V8inj5+mgY0vNVtPPRQhZ66y+kD8DfamBJRevCDc529nP4fd689NT6/TOP0dglNwFVPcTjSGRbE/AXRBNqCT2ySQvwz/kg3KTt+DN7QINytb/lTXZg5fDvGH2ONNnQhNVIkOJgrHf3A3DrIgOhYOxt5LaFRO59LgEV9OUYbQyjXJ61oqnx6+6d4DRV9G9Mb4alhlEsIqVezc1/7+N/GSwnYrxXRE3snVSetUeGDP7F9gd0DFcyb9KPkLruIPRQraaBw/wpGTqlfyUqpYVyoDADipxNL5T1tmllVQ0= ishipulin@Igors-MacBook-Pro.local
          script: cd spacey-app && sudo docker pull supergrovernn/spacey:latest && sudo docker-compose up -d --no-deps spacey-app