name: Deploy

on:
  push:
    branches:
<<<<<<< HEAD
      - [ main, test-deploy ]
=======
      - test-deploy
>>>>>>> ae0d1cfb631a96d6199f8dc33e17423a8545cd3e

jobs:
  push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: supergrovernn/spacey:latest
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd spacey-app && sudo docker pull supergrovernn/spacey:latest && sudo docker-compose up -d --no-deps
          