name: Test

on:
  push:
  pull_request:
    branches: [ test-deploy ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with:
        nide-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test