name: Yandex Deploy

on:
  push:
    branches:
      - test-deploy

jobs:
  push-docker-image:
    name: Copy files and build on YA.Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd app 